<a href="https://colab.research.google.com/github/anshul567/Machine-Learning-Lab/blob/master/PERCEPTRON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron Learning Algorithm Code

In [0]:
import numpy as np

In [7]:
W = np.zeros(2+1)
W

array([0., 0., 0.])

In [8]:
X=[2,3]
np.insert(X, 0, 1)


array([1, 2, 3])

# The complete executable code of Perceptron model

In [0]:
 
class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=2, epochs=50):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    
    def activation_fn(self, x):
        #return (x >= 0).astype(np.float32)
        return 1 if x >= 0 else 0
 
    def predict(self, x):
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
 
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                x = np.insert(X[i], 0, 1)
                y = self.predict(x)
                e = d[i] - y
                self.W = self.W + self.lr * e * x

# AND GATE EXAMPLE WITH NO OF SAMPLES/RECORDS AS 4 AND EPOCHS AS 100

In [10]:
if __name__ == '__main__':
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
    d = np.array([0, 0, 0, 1])
 
    perceptron = Perceptron(input_size=2)
    perceptron.fit(X, d)
    print(perceptron.W)

[-6.  4.  2.]


# Using the AND gate data, we should get a weight vector of [-3, 2, 1]. This means that the bias is -3 and the weights are 2 and 1 for x_1 and x_2, respectively.

# LETS TEST MANUALLY
# let us test for x=[0, 1]

In [11]:
x=[1, 0, 1]
y= -3*1+2*0+1*1
y

-2

# since it is a negative value on applying activation function we get zero which is correct